[build]
  base = "apps/web"
  publish = "out"
  command = "pnpm run build"

[[redirects]]
  from = "/api/*"
  to = "https://api.thepaulieffect.com/pare/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/artifacts/*"
  to = "https://api.thepaulieffect.com/pare/artifacts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/frames/*"
  to = "https://api.thepaulieffect.com/pare/frames/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200