import type { CSSProperties } from 'react';

const studioUrl = '/';
const repoUrl = 'https://github.com/executiveusa/PARE';

const letters = [
  ['C','U','E','H','M','Q','L'],
  ['N','O','G','T','S','V','B'],
  ['Y','P','A','R','É','X','Z'],
  ['D','F','J','K','W','I','C'],
  ['S','M','O','L','Q','H','N'],
];
const target = new Set(['2-1','2-2','2-3','2-4']);
const drifts = [
  ['-24px','-18px'],['18px','-28px'],['-14px','20px'],['26px','10px'],['-20px','26px'],['18px','18px'],['-28px','8px'],
  ['22px','-16px'],['-18px','-24px'],['24px','22px'],['-20px','14px'],['16px','-18px'],['-12px','28px'],['22px','16px'],
  ['-20px','-12px'],['0','0'],['0','0'],['0','0'],['0','0'],['20px','-14px'],['-16px','20px'],
  ['26px','-20px'],['-18px','16px'],['16px','24px'],['-24px','-12px'],['22px','18px'],['-12px','-24px'],['18px','14px'],
  ['-16px','22px'],['20px','-16px'],['-22px','-18px'],['18px','26px'],['-24px','10px'],['14px','-20px'],['24px','20px'],
];

const css = String.raw`
:root{--pp:#f4f3ef;--ink:#11110f;--muted:rgba(17,17,15,.42);--line:rgba(17,17,15,.12);--dark:#0b0b0a;--light:#f4f3ef;--ease:cubic-bezier(.22,1,.36,1)}
*{box-sizing:border-box}.parePreview{min-height:100vh;background:var(--pp);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:clip}.parePreview *{box-sizing:border-box}.parePreview a{color:inherit}.nav{position:fixed;inset:0 0 auto;z-index:80;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;height:68px;padding:0 22px;mix-blend-mode:difference;color:#fff;pointer-events:none}.nav>*{pointer-events:auto}.brand,.enter{display:inline-flex;align-items:center;min-height:44px;text-decoration:none}.brand{font-size:13px;font-weight:600;letter-spacing:-.02em}.mark{font:300 18px/1 ui-monospace,SFMono-Regular,Menlo,monospace}.enter{justify-self:end;font-size:12px;border-bottom:1px solid currentColor}.parePreview a:focus-visible{outline:2px solid currentColor;outline-offset:4px}
.hero{position:relative;min-height:220vh}.sticky{position:sticky;top:0;min-height:100svh;overflow:hidden;display:grid;place-items:center;padding:84px 20px 48px}.grid{width:min(720px,84vw);aspect-ratio:1.38;display:grid;grid-template-columns:repeat(7,1fr);grid-template-rows:repeat(5,1fr);place-items:center}.letter{display:grid;place-items:center;width:100%;height:100%;font:300 clamp(14px,1.6vw,24px)/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);opacity:1;transform:translate3d(0,0,0) scale(1);transition:opacity .7s var(--ease),transform .8s var(--ease),filter .7s var(--ease),color .5s ease}.letter[data-target=true]{font-family:inherit;font-weight:400;font-size:clamp(34px,5vw,78px);letter-spacing:-.06em;color:var(--ink)}.hero[data-stage="1"] .letter:not([data-target=true]){opacity:.26}.hero[data-stage="2"] .letter:not([data-target=true]){opacity:0;filter:blur(8px);transform:translate3d(var(--dx),var(--dy),0) scale(.88)}.hero[data-stage="2"] .letter[data-target=true]{transform:scale(1.05)}.hero[data-stage="3"] .letter:not([data-target=true]){opacity:0}.hero[data-stage="3"] .letter[data-target=true]{transform:translateY(-7vh) scale(1.08)}.note,.cue{position:absolute;bottom:24px;font:300 11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}.note{left:22px}.cue{right:22px}.hero[data-stage="2"] .note{opacity:0}
.definition{min-height:100svh;padding:18vh 7vw 10vh;display:grid;grid-template-columns:1fr 1fr;gap:8vw;align-items:end;border-top:1px solid var(--line)}.word{align-self:start}.word h2{margin:0;font-size:clamp(82px,17vw,270px);line-height:.78;letter-spacing:-.085em;font-weight:300}.word p{margin:34px 0 0;font:300 13px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}.meaning{max-width:560px;padding-bottom:2vh}.part{display:block;margin-bottom:28px;font:300 12px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}.meaning p{margin:0;font-size:clamp(34px,5vw,76px);line-height:1.02;letter-spacing:-.055em;font-weight:300}
.quote{position:relative;min-height:160svh;background:var(--dark);color:var(--light)}.quoteSticky{position:sticky;top:0;min-height:100svh;display:grid;place-items:center;padding:12vh 8vw;overflow:hidden}.quoteCopy{max-width:1200px;text-align:center}.quoteCopy p{margin:0;font-weight:300;font-size:clamp(36px,6.8vw,108px);line-height:.98;letter-spacing:-.06em}.q1,.q2{display:block;transition:opacity .6s var(--ease),transform .7s var(--ease)}.q1{opacity:.28;transform:translateY(14px)}.q2{margin-top:.2em;opacity:.18;transform:translateY(18px)}.quote[data-stage="1"] .q1{opacity:1;transform:none}.quote[data-stage="2"] .q1{opacity:.28}.quote[data-stage="2"] .q2{opacity:1;transform:none}.credit{position:absolute;bottom:28px;left:50%;transform:translateX(-50%);width:max-content;font:300 10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;text-transform:uppercase;color:rgba(244,243,239,.48)}
.noise{position:relative;min-height:210svh}.noiseSticky{position:sticky;top:0;min-height:100svh;overflow:hidden;display:grid;place-items:center}.noiseWord{position:absolute;font:300 clamp(12px,1.5vw,20px)/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.05em;text-transform:uppercase;color:var(--muted);transition:opacity .65s var(--ease),transform .8s var(--ease),filter .7s var(--ease)}.noiseWord:nth-child(1){left:8%;top:16%}.noiseWord:nth-child(2){left:32%;top:11%}.noiseWord:nth-child(3){right:9%;top:20%}.noiseWord:nth-child(4){left:16%;top:47%}.noiseWord:nth-child(5){right:18%;top:45%}.noiseWord:nth-child(6){left:9%;bottom:17%}.noiseWord:nth-child(7){left:43%;bottom:14%}.noiseWord:nth-child(8){right:8%;bottom:18%}.noiseWord:nth-child(9){right:37%;top:33%}.noiseWord:nth-child(10){left:39%;top:61%}.noise[data-stage="1"] .noiseWord{color:rgba(17,17,15,.68);transform:scale(1.04)}.noise[data-stage="2"] .noiseWord{opacity:0;filter:blur(8px);transform:scale(.9) translateY(20px)}.prompt{position:relative;z-index:3;width:min(760px,calc(100vw - 40px));border-bottom:1px solid var(--ink);padding:0 0 18px;font-size:clamp(28px,4.8vw,68px);line-height:1;letter-spacing:-.05em;font-weight:300;opacity:0;transform:translateY(24px);transition:opacity .8s var(--ease),transform .9s var(--ease)}.noise[data-stage="2"] .prompt{opacity:1;transform:none}.prompt small{display:block;margin-top:24px;font:300 10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}
.studio{min-height:120svh;padding:12vh 5vw;background:#e8e7e1;border-top:1px solid var(--line)}.eyebrow{display:flex;align-items:center;justify-content:space-between;margin-bottom:32px;font:300 10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}.frame{min-height:76svh;display:grid;grid-template-columns:minmax(280px,.68fr) 1.32fr;border:1px solid rgba(17,17,15,.16);background:var(--pp);box-shadow:0 24px 80px rgba(17,17,15,.08)}.chat{padding:clamp(24px,4vw,56px);border-right:1px solid var(--line);display:flex;flex-direction:column;justify-content:space-between}.chat h3{margin:0;font-size:clamp(34px,4.5vw,72px);line-height:.95;letter-spacing:-.055em;font-weight:300}.chat p{max-width:28em;margin:20px 0 0;font-size:14px;line-height:1.7;color:var(--muted)}.status{display:grid;gap:10px;margin-top:48px}.status span{display:flex;justify-content:space-between;gap:20px;padding-top:10px;border-top:1px solid var(--line);font:300 10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.05em}.status em{font-style:normal;color:var(--muted)}.canvas{position:relative;display:grid;place-items:center;overflow:hidden;background:#11110f;color:#f4f3ef;padding:40px}.canvas:before{content:"";position:absolute;inset:18px;border:1px solid rgba(244,243,239,.12)}.canvasWord{font-size:clamp(56px,10vw,160px);line-height:.78;letter-spacing:-.08em;font-weight:300}.canvasNote{position:absolute;left:32px;bottom:28px;font:300 9px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em;color:rgba(244,243,239,.48)}
.engines{min-height:100svh;padding:16vh 7vw;display:grid;align-content:center;border-top:1px solid var(--line)}.kicker{font:400 11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.11em;text-transform:uppercase}.engines h2{margin:0;max-width:1000px;font-size:clamp(50px,9vw,140px);font-weight:300;line-height:.88;letter-spacing:-.07em}.engineLine{margin-top:8vh;display:grid;grid-template-columns:repeat(6,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.engine{padding:24px 8px;text-align:center;font:300 10px/1.3 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);border-right:1px solid var(--line)}.engine:last-child{border-right:0}.truth{margin-top:32px;font-size:clamp(22px,3vw,42px);line-height:1.1;letter-spacing:-.035em;font-weight:300}
.own{min-height:100svh;background:var(--dark);color:var(--light);padding:16vh 7vw;display:grid;align-content:center}.ownStack{display:grid}.ownStack span{border-top:1px solid rgba(244,243,239,.15);padding:13px 0 16px;font-size:clamp(40px,8.5vw,132px);line-height:.9;letter-spacing:-.065em;font-weight:300}.ownStack span:last-child{border-bottom:1px solid rgba(244,243,239,.15)}.ownFoot{display:flex;justify-content:space-between;gap:30px;align-items:flex-end;margin-top:44px;color:rgba(244,243,239,.48)}.ownFoot p{max-width:420px;margin:0;font-size:14px;line-height:1.65}.ownFoot strong{font:400 11px/1.3 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--light)}
.final{min-height:100svh;display:grid;place-items:center;padding:10vh 24px;text-align:center}.final h2{margin:0;font-size:clamp(92px,22vw,360px);line-height:.72;letter-spacing:-.095em;font-weight:300}.final p{margin:44px 0 0;font:300 11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.finalEnter{display:inline-flex;align-items:center;gap:14px;min-height:44px;margin-top:38px;border-bottom:1px solid var(--ink);text-decoration:none;font-size:16px}.source{display:inline-flex;align-items:center;min-height:44px;margin-top:18px;font:300 10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);text-decoration:none}
[data-reveal]{opacity:1;transform:none}.pare-motion [data-reveal]{opacity:0;transform:translateY(28px);transition:opacity .8s var(--ease),transform .9s var(--ease)}.pare-motion [data-reveal].is-visible{opacity:1;transform:none}
@media(max-width:760px){.nav{height:58px;padding:0 max(14px,env(safe-area-inset-right)) 0 max(14px,env(safe-area-inset-left))}.hero{min-height:190vh}.sticky{padding:68px 12px 42px}.grid{width:94vw;aspect-ratio:.95}.letter{font-size:11px}.letter[data-target=true]{font-size:clamp(30px,9vw,48px)}.note{left:14px;bottom:max(16px,env(safe-area-inset-bottom));font-size:9px}.cue{right:14px;bottom:max(16px,env(safe-area-inset-bottom));font-size:9px}.definition{min-height:auto;grid-template-columns:1fr;gap:15vh;padding:14vh 18px 12vh}.word h2{font-size:34vw}.word p{margin-top:24px}.meaning p{font-size:12vw}.quote{min-height:140svh}.quoteSticky{padding:10vh 20px}.quoteCopy p{font-size:12vw}.credit{bottom:20px;font-size:8px}.noise{min-height:175svh}.noiseWord{font-size:9px}.prompt{width:calc(100vw - 28px);font-size:10.5vw;padding-bottom:14px}.studio{min-height:auto;padding:10vh 12px}.frame{min-height:auto;grid-template-columns:1fr}.chat{min-height:58svh;border-right:0;border-bottom:1px solid var(--line);padding:28px 22px}.canvas{min-height:66svh}.engines{min-height:auto;padding:14vh 18px}.engines h2{font-size:17vw}.engineLine{grid-template-columns:repeat(2,1fr)}.engine{border-bottom:1px solid var(--line)}.engine:nth-child(2n){border-right:0}.own{min-height:auto;padding:14vh 18px}.ownStack span{font-size:15vw}.ownFoot{align-items:flex-start;flex-direction:column}.final h2{font-size:31vw}.final{min-height:90svh}}
@media(prefers-reduced-motion:reduce){.parePreview *,.parePreview *:before,.parePreview *:after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.01ms!important}.letter:not([data-target=true]){opacity:.18}.prompt{opacity:1;transform:none}}
`;

const script = String.raw`(()=>{const root=document.querySelector('[data-pare-preview]');if(!root)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const scenes=[...root.querySelectorAll('[data-scroll-scene]')];const stageFor=(el,stops)=>{const r=el.getBoundingClientRect(),travel=Math.max(1,r.height-innerHeight),p=Math.min(1,Math.max(0,-r.top/travel));let s=0;stops.forEach((x,i)=>{if(p>=x)s=i+1});return s};let ticking=false;const update=()=>{ticking=false;if(reduced)return;for(const el of scenes){const kind=el.getAttribute('data-scroll-scene');const stops=kind==='hero'?[.16,.42,.72]:kind==='quote'?[.24,.62]:[.22,.58];el.setAttribute('data-stage',String(stageFor(el,stops)))}};if(!reduced){root.classList.add('pare-motion');addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update,{passive:true});update()}else{scenes.forEach(el=>el.setAttribute('data-stage','2'))}if('IntersectionObserver'in window&&!reduced){const io=new IntersectionObserver(es=>{for(const e of es)if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}},{threshold:.14,rootMargin:'0px 0px -6% 0px'});root.querySelectorAll('[data-reveal]').forEach(el=>io.observe(el))}else{root.querySelectorAll('[data-reveal]').forEach(el=>el.classList.add('is-visible'))}})();`;

export const metadata = {
  title: 'PARÉ — Design operating system',
  description: 'Remove what is unnecessary. Keep what makes the work stronger.',
};

export default function ParePreviewPage() {
  return (
    <main className='parePreview' data-pare-preview>
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <nav className='nav' aria-label='Primary'>
        <a className='brand' href='#top'>PARÉ</a><span className='mark' aria-hidden='true'>×</span><a className='enter' href={studioUrl}>Enter studio</a>
      </nav>

      <section id='top' className='hero' data-stage='0' data-scroll-scene='hero' aria-label='PARÉ word reveal'>
        <div className='sticky'>
          <div className='grid' aria-hidden='true'>
            {letters.flatMap((row,r)=>row.map((letter,c)=>{const d=drifts[r*7+c];return <span key={`${r}-${c}`} className='letter' data-target={target.has(`${r}-${c}`)} style={{'--dx':d[0],'--dy':d[1]} as CSSProperties}>{letter}</span>}))}
          </div>
          <div className='note'>Design operating system<br/>Open source / owner controlled</div><div className='cue'>scroll</div>
        </div>
      </section>

      <section className='definition' aria-labelledby='definition-title'>
        <div className='word' data-reveal><h2 id='definition-title'>PARÉ</h2><p>pare /per/<br/>verb</p></div>
        <div className='meaning' data-reveal><span className='part'>01 / the idea</span><p>To remove what is unnecessary until only what matters remains.</p></div>
      </section>

      <section className='quote' data-stage='0' data-scroll-scene='quote' aria-label='Design principle'>
        <div className='quoteSticky'><div className='quoteCopy'><p><span className='q1'>Nothing more to add.</span><span className='q2'>Nothing left to take away.</span></p></div><div className='credit'>After Antoine de Saint-Exupéry</div></div>
      </section>

      <section className='noise' data-stage='0' data-scroll-scene='noise' aria-labelledby='noise-title'>
        <div className='noiseSticky'>
          {['tools','models','plugins','dashboards','menus','workflows','prompts','settings','providers','options'].map(word=><span className='noiseWord' key={word}>{word}</span>)}
          <div className='prompt' id='noise-title'>What are we making?<small>One Hands / start with the outcome</small></div>
        </div>
      </section>

      <section className='studio' aria-labelledby='studio-title'>
        <div className='eyebrow' data-reveal><span>02 / complexity disappears</span><span>PARÉ Studio</span></div>
        <div className='frame' data-reveal><div className='chat'><div><h3 id='studio-title'>Build the official brand for this company.</h3><p>PARÉ keeps the conversation simple while One Hands coordinates strategy, creation, critique, proof and the agent runtime behind it.</p></div><div className='status' aria-label='Example workflow'><span>Understand <em>complete</em></span><span>Reduce <em>complete</em></span><span>Create <em>working</em></span><span>Critique <em>next</em></span><span>Prove <em>human gate</em></span></div></div><div className='canvas' aria-label='Example PARÉ canvas'><div className='canvasWord'>PARÉ</div><div className='canvasNote'>Live canvas / project truth stays portable</div></div></div>
      </section>

      <section className='engines' aria-labelledby='engines-title'><div className='kicker' data-reveal>03 / runtime neutral</div><h2 id='engines-title' data-reveal>One request.<br/>Many engines.</h2><div className='engineLine' data-reveal>{['CODEX','CLAUDE','GEMINI','OPENCODE','HERMES','PI'].map(x=><div className='engine' key={x}>{x}</div>)}</div><p className='truth' data-reveal>PARÉ is the system. The agent is replaceable.</p></section>

      <section className='own' aria-labelledby='own-title'><div className='kicker' id='own-title' data-reveal>04 / open by default</div><div className='ownStack' data-reveal><span>Your projects.</span><span>Your files.</span><span>Your agents.</span><span>Your infrastructure.</span></div><div className='ownFoot' data-reveal><p>Run PARÉ yourself. Connect the agents you already use. Keep the project as portable files. Hosted infrastructure can be convenient; ownership should not depend on it.</p><strong>Apache-2.0 / open source</strong></div></section>

      <section className='final' aria-labelledby='final-title'><div><h2 id='final-title' data-reveal>PARÉ</h2><p data-reveal>Remove what does not serve the idea.</p><a className='finalEnter' href={studioUrl} data-reveal>Enter PARÉ →</a><br/><a className='source' href={repoUrl} data-reveal>View source ↗</a></div></section>
      <script dangerouslySetInnerHTML={{ __html: script }} />
    </main>
  );
}
